### ISSUE TITLE
Optional logger script loading

### ISSUE THREAD

**Issue by VolodymyrBiryuk** [OpenReqEU/openreq-live#1]
Please include an option in the user profile settings to opt-in to user interaction logging (implicit feedback). Load the logging script only if user opted in. The state of user agreement could be stored in the necessary cookies across sessions.

**Comment by mstettinger** [comment]
We included this functionality in the cookie consent - if the user do not accept it the script will not be loaded.

**Comment by dfucci** [comment]
@VolodymyrBiryuk is this closed by cf52ee6abbb078ba1b504879cd17629eed1f498e?
