### ISSUE TITLE
Access to personal data in user profile

### ISSUE THREAD

**Issue by VolodymyrBiryuk** [OpenReqEU/openreq-live#2]
The user profile view needs a possibility to acess all logged data of the specific user to be GDPR compliant.

**Comment by mstettinger** [comment]
Sorry I am not sure if I understand exactly what you mean ... ?

**Comment by VolodymyrBiryuk** [comment]
If the implicit feebck logger is integrated into the OpenReq Live UI and user interaction data is collected the user must be able to know what exactly is collected. For example Also the user must be able to download what has been collected on them so far. This can be a JSON or text file with all the data we have on a specific user. I can provide an endpoint that takes the user id as parameter and returns a JSON file with the relevant user data. Furthermore a user must be able to delete the data we have on them. The two relevant buttons can be placed somewhere in the MyProfile view:

![image](https://user-images.githubusercontent.com/19716910/59421793-7d36c980-8dcf-11e9-8593-18fc984feedc.png)

**Comment by mstettinger** [comment]
Sounds good - please provide us the Endpoints and we integrate it @ the user detail page ....

Thanks & best regards,
Martin

**Comment by dfucci** [comment]
> I can provide an endpoint that takes the user id as parameter and returns a JSON file with the relevant user data. Furthermore a user must be able to delete the data we have on them. The two relevant buttons can be placed somewhere in the MyProfile view:

@VolodymyrBiryuk what is the status of the endpoints you proposed?

**Comment by VolodymyrBiryuk** [comment]
I have the endpoints, but we need to agree on how we can restrict the access to the data so the user can only view/delete only their own data. For example the request has to be done from the backend to not expose the access token.

**Comment by mstettinger** [comment]
Thanks for your message.
- Which user-specific data is recorded ?
- How should the authentication take place ?

We thought that having maybe in the profile setting of the user the possibility to check the recorded user-specific data ... is it really necessary that the user itself can delete the data ? Isn't it enough to allow the user a request for deleting his data that he has then to approve a mail message maybe ?

Other idea:
users are registered with an mail address - maybe it is easier if the user selects "View my recorded data" and he / she gets a mail message with a unique link to access his / her data ? with this we also can restrict the access to the user itself ...

what do you think ?

**Comment by LloydThinks** [comment]
@VolodymyrBiryuk , do you have an update/response on this?

**Comment by VolodymyrBiryuk** [comment]
As for the user data, the interaction with the requirement UI elemt is recorded:

- Text input (changes made on the title and description)
- Clicks (changes made to the status of a requirement)

> allow the user a request for deleting his data
This is probably enough to be GDPR conformat.

> "View my recorded data" and he / she gets a mail message with a unique link to access his / her data ?
Where will the link be generated. Maybe it's simpler to send the JSON as attachment with the email.

**Comment by LloydThinks** [comment]
As per GDPR, the data doesn't have to be immediately available and deletable via some UI. They can simply email the developer and request the data (or request that the data is deleted), and then you have 30 days (I think) to respond to the request. In this case, you have to manually pull all data you have on this user and send it to them in some standard format (or delete it).

My recommendation for this issue is to add a note to the User Profile page at https://live.openreq.eu/user/profile: "To request data per GDPR regulations, send an email to <email here>."

Thoughts @VolodymyrBiryuk and @mstettinger ? We should handle and close this issue soon. I believe adding that text to the User Profile page is a simple and quick change to satisfy this concern.
